version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_slow.log:/var/log/mysql_slow.log
    command: >
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql_slow.log
      --long-query-time=1
      --log-queries-not-using-indexes=1
    ports:
      - "3306:3306"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./mysql_slow.log:/var/log/mysql_slow.log
    depends_on:
      - mysql

  # ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - "discovery.type=single-node"
      - "cluster.name=elasticsearch-main-cluster"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    mem_limit: 1g
    cpu_shares: 512

  logstash:
    image: docker.elastic.co/logstash/logstash:8.0.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  #####################################################################################################################
  # Graylog Stack
  graylog:
    image: graylog/graylog:4.3
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=<password-sha2>
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    depends_on:
      - mongo
      - elasticsearch_graylog
    ports:
      - "9000:9000"

  mongo:
    image: mongo:4.2
    volumes:
      - ./mongo_data:/data/db

  elasticsearch_graylog:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - "discovery.type=single-node"
      - "cluster.name=elasticsearch-graylog-cluster"
    volumes:
      - ./es_graylog_data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9301:9300"
    mem_limit: 1g
    cpu_shares: 512

  filebeat_graylog:
    image: docker.elastic.co/beats/filebeat:7.17.0
    volumes:
      - ./filebeat_graylog.yml:/usr/share/filebeat/filebeat.yml
      - ./mysql_slow.log:/var/log/mysql_slow.log
    depends_on:
      - graylog

#####################################################################################################################
#metrics:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "8080:8080"