version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./logs:/var/log/mysql
    ports:
      - "3306:3306"

  # ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    mem_limit: 2g
    cpu_shares: 512
    ports:
      - 9200:9200

  elasticsearch-exporter:
    image: prometheuscommunity/elasticsearch-exporter:latest
    environment:
      - ES_URI=http://elasticsearch:9200
    ports:
      - 9114:9114
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601

  filebeat-elk:
    image: docker.elastic.co/beats/filebeat:8.5.0
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log/mysql
    depends_on:
      - elasticsearch
      - logstash
      - kibana

  # GrayLog Stack
  graylog:
    image: graylog/graylog:4.2
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_USERNAME=admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=415e8a6ba1c3eb93e81df34731acc3d60efee685c8e6f7412592a45ba3a0e3b0
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    ports:
      - 9000:9000
      - 12201:12201/udp  # GELF input
    depends_on:
      - mongo
      - elasticsearch-graylog

  mongo:
    image: mongo:4.2

  elasticsearch-graylog:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node

  filebeat-graylog:
    image: docker.elastic.co/beats/filebeat:8.5.0
    volumes:
      - ./filebeat_graylog.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log/mysql
    depends_on:
      - graylog

  # Monitoring - Prometheus and Grafana
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.5.0
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    environment:
      - setup.kibana.host=http://kibana:5601
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
    depends_on:
      - elasticsearch
      - kibana
      - graylog

volumes:
  mysql_data:
  logs:
