metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

# System-level monitoring
metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - memory
      - network
      - diskio
      - filesystem
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~

  # Container-level monitoring (including ELK and Graylog)
  - module: docker
    metricsets: ["container", "cpu", "diskio", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    processors:
      - add_docker_metadata: ~
